name: Pipeline DevSecOps B치sico

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "18"

jobs:
  analisis-codigo:
    name: 游댌 An치lisis de C칩digo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout c칩digo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar ESLint
      run: npm run lint:security || true

  build-and-scan:
    name: 游냡 Build + Trivy Scan
    runs-on: ubuntu-latest
    needs: analisis-codigo

    steps:
    - name: Checkout c칩digo
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: miapp-segura:latest

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: miapp-segura:latest
        format: table

    - name: Probar contenedor (endpoint b치sico)
      run: |
        docker run -d -p 3000:3000 --name test-app miapp-segura:latest
        sleep 10
        curl -f http://localhost:3000/login || exit 1
        docker stop test-app
        docker rm test-app
